appname/config/routes.rb
  Rails.application.routes.draw do
    resources :users
    resources :books
    get 'books/show_subjects'
  end

appname/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

appname/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :subject
  validates_presence_of :title
  validates_numericality_of :price, :message=>"Error Message"
end

appname/app/models/subject.rb
class Subject < ApplicationRecord
  has_many :books
end

appname/app/models/user.rb
class User < ApplicationRecord
end

appname/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

appname/app/controllers/book_controller.rb
class BookController < ApplicationController
  def list
      @books = Book.all
   end

   def show
      @book = Book.find(params[:id])
   end

   def new
      @book = Book.new
      @subjects = Subject.all
   end

   def book_params
      params.require(:books).permit(:title, :price, :subject_id, :description)
   end

   def create
      @book = Book.new(book_params)

      if @book.save
         redirect_to :action => 'list'
      else
         @subjects = Subject.all
         render :action => 'new'
      end
   end

   def edit
      @book = Book.find(params[:id])
      @subjects = Subject.all
   end

   def book_param
      params.require(:book).permit(:title, :price, :subject_id, :description)
   end

   def update
      @book = Book.find(params[:id])

      if @book.update_attributes(book_param)
         redirect_to :action => 'show', :id => @book
      else
         @subjects = Subject.all
         render :action => 'edit'
      end
   end

   def delete
      Book.find(params[:id]).destroy
      redirect_to :action => 'list'
   end

   def show_subjects
      @subject = Subject.find(params[:id])
   end

end

appname/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
      @books = Book.all
      @subject = Subject.all
   end
   def list
   @books = Book.all
  end

   def show
      @book = Book.find(params)
   end

   def new
      @book = Book.new
      @subjects = Subject.all
   end

   def book_params
      params.require(:books).permit(:title, :price, :subject_id, :description)
   end

   def create
      @book = Book.new(book_params)

      if @book.save
         redirect_to books_path
      else
         @subjects = Subject.all
         render :action => 'new'
      end
   end

   def edit
      @book = Book.find(params[:id])
      @subjects = Subject.all
   end

   def book_param
      params.require(:book).permit(:title, :price, :subject_id, :description)
   end

   def update
      @book = Book.find(params[:id])

      if @book.update_attributes(book_param)
         redirect_to :action => 'show', :id => @book
      else
         @subjects = Subject.all
         render :action => 'edit'
      end
   end

   def destroy
      Book.find(params[:id]).destroy
      redirect_to books_path
   end

   def show_subjects
      @subject = Subject.find(params[:id])
   end
end

appname/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user= User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def user_params
   params.require(:user).permit(:name, :roll)
  end
end

appname/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    "welcome to the rails"
  end
end

appname/app/helpers/application_helper.rb
module ApplicationHelper
end

appname/app/helpers/book_helper.rb
module BookHelper
end

appname/app/helpers/users_helper.rb
module UsersHelper
end

appname/app/helpers/welcome_helper.rb
module WelcomeHelper
end

appname/app/views/book/delete.html.erb
<li>
   <%= link_to c.title, {:action => 'show', :id => c.id} -%>
   <b> <%= link_to 'Edit', {:action => 'edit', :id => c.id} %></b>
   <b> <%= link_to "Delete", {:action => 'delete', :id => c.id},
      :confirm => "Are you sure you want to delete this item?" %></b>
</li>

appname/app/views/book/edit.html.erb
<h1>Edit Book Detail</h1>

<%= form_for @book, :url =>{:action => "update", :id =>@book} do |f| %>

<p>Title: <%= f.text_field 'title' %></p>
<p>Price: <%= f.text_field  'price' %></p>
<p>Subject: <%= f.collection_select :subject_id, Subject.all, :id, :name %></p>
<p>Description<br/>

<%= f.text_area 'description' %></p>
<%= f.submit "Save changes" %>
<% end %>

<%= link_to 'Back', {:action => 'list' } %>

appname/app/views/book/index.html.erb
<% if @books.blank? %>
<p>There are not any books currently in the system.</p>
<% else %>
<p>These are the current books in our system</p>

<ul id = "books">
   <% @books.each do |c| %>
   <li><%= link_to c.title, {:action => 'show', :id => c.id} -%></li>
   <% end %>
</ul>

<% end %>
<p><%= link_to "Add new Book", {:action => 'new' }%></p>

appname/app/views/book/list.html.erb
<% if @books.blank? %>
<p>There are not any books currently in the system.</p>
<% else %>
<p>These are the current books in our system</p>

<ul id = "books">
   <% @books.each do |c| %>
   <li><%= link_to c.title, {:action => 'show', :id => c.id} -%></li>
   <% end %>
</ul>

<% end %>
<p><%= link_to "Add new Book", {:action => 'new' }%></p>

appname/app/views/book/new.html.erb
<h1>Add new book</h1>

<%= form_tag :action => 'create' do %>
<p><label for = "book_title">Title</label>:

<%= text_field 'books', 'title' %></p>
<p><label for = "book_price">Price</label>:

<%= text_field 'books', 'price' %></p>
<p><label for = "book_subject_id">Subject</label>:

<%= collection_select(:books, :subject_id, @subjects, :id, :name, prompt: true) %></p>
<p><label for = "book_description">Description</label><br/>

<%= text_area 'books', 'description' %></p>
<%= submit_tag "Create" %>

<% end -%>
<%= link_to 'Back', {:action => 'list'} %>

appname/app/views/book/show.html.erb
<h1><%= @book.title %></h1>

<p>
   <strong>Price: </strong> $<%= @book.price %><br />
   <strong><%= link_to @book.subject.name, book_path(@book) %></strong>
   <strong>Created Date:</strong> <%= @book.created_at %><br />
<strong>Subject: </strong> <%= link_to @book.subject.name,
:action => "show_subjects", :id => @book.subject.id %><br />
</p>

<p><%= @book.description %></p>

<hr />

<%= link_to 'Back', books_path %>

appname/app/views/book/show_subjects.html.erb
<h1><%= @subject.name -%></h1>

<ul>
   <% @subject.books.each do |c| %>
   <li><%= link_to c.title, :action => "show", :id => c.id -%></li>
   <% end %>
</ul>

appname/app/views/users/add.html.erb
<h1>Add new </h1>
<p>Roll : <%= @user.roll %></p>
<P>Name : <%= @user.name %></P>

appname/app/views/users/index.html.erb
<h1> welcome</h1>

<table border="1">
  <tr>
    <th>Roll</th>
    <th>Name</th>
  </tr>
  <% @user.each do |user| %>
    <tr>
      <td><%= user.roll %></td>
      <td><%= link_to user.name, user_path(user) %></td>
    </tr>
  <% end %>
</table>
<hr />
<p> <%= link_to 'new', {:action => 'new'} %> </p>

appname/app/views/users/new.html.erb
<h1>Add new User</h1>

<%= form_for @user do |form| %>
  <p>
    Name : <%= form.text_field :name%>
  </p>
  <p>
    Roll : <%= form.text_field :roll%>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end -%>

appname/app/views/users/show.html.erb
<p>Roll : <%= @user.roll %></p>
<P>Name : <%= @user.name %></P>